### ISSUE TITLE
Website updated

### ISSUE THREAD

**Issue by raycekar** [Syzygianinfern0/Chase-Activate-All-Offers#1]
Giving the heads up it seems the website has updated and going back to all the offers, you have to scroll down to load the other offers (from what i can tell) or the script wont see them.

**Comment by Syzygianinfern0** [comment]
It seems to work alright for me. All of the offers on the page are detected. 

Could you try using the extension called "Selector Gadget" and click on the plus signs and see if it detects all the offers on the page?

**Comment by yuyujiaug** [comment]
> It seems to work alright for me. All of the offers on the page are detected.
> 
> Could you try using the extension called "Selector Gadget" and click on the plus signs and see if it detects all the offers on the page?

Your script is not working today May 17, 2024. I get message 

> Element not found, stopped the interval.

Using the Selector Gadget, the element `.horizontal-margin` is recognized. Can you please update the script?

**Comment by yuyujiaug** [comment]
I have fixed the issue after checking the Add Offer and Already Active offer elements. It seems that they have changed.
The original values `._4jplu9 .horizontal-margin` don't work
The new values `._1bof7fb9 .horizontal-margin` work

**Comment by Syzygianinfern0** [comment]
Thanks for reporting! It had updated for me today as well.
